/**
 * Hooks Manifest
 * Complete metadata for all 27 hooks with relevance conditions
 */

import type { HookMetadata } from "../shared/types.js";

export const HOOKS_MANIFEST: HookMetadata[] = [
  // ═══ PreToolUse — Edit|Write ═══════════════════════════════════════════════
  {
    id: "guard-files",
    name: "File Guard",
    description: "Blocks editing .env, credentials, secrets, and other sensitive files",
    event: "PreToolUse",
    matcher: "Edit|Write",
    script: "pre-tool-use/guard-files.sh",
    category: "security",
    tier: "core",
    requires: {},
    timeout: 5,
  },
  {
    id: "secret-scanner",
    name: "Secret Scanner",
    description: "Scans content for API keys, passwords, tokens before writing",
    event: "PreToolUse",
    matcher: "Edit|Write",
    script: "pre-tool-use/secret-scanner.sh",
    category: "security",
    tier: "core",
    requires: {},
    timeout: 5,
  },

  // ═══ PreToolUse — Bash ═════════════════════════════════════════════════════
  {
    id: "guard-commands",
    name: "Command Guard",
    description: "Blocks dangerous bash commands (rm -rf, drop table, etc.)",
    event: "PreToolUse",
    matcher: "Bash",
    script: "pre-tool-use/guard-commands.sh",
    category: "security",
    tier: "core",
    requires: {},
    timeout: 5,
  },
  {
    id: "commit-lint",
    name: "Commit Lint",
    description: "Validates commit messages follow conventional commit format",
    event: "PreToolUse",
    matcher: "Bash",
    script: "pre-tool-use/commit-lint.sh",
    category: "workflow",
    tier: "recommended",
    requires: {},
    timeout: 5,
  },

  // ═══ PostToolUse — Edit|Write ══════════════════════════════════════════════
  {
    id: "detect-project",
    name: "Project Detector",
    description: "Auto-detects project type and configures MCPs per-project",
    event: "PostToolUse",
    matcher: "Edit|Write",
    script: "post-tool-use/detect-project.sh",
    category: "workflow",
    tier: "core",
    requires: {},
    timeout: 5,
  },
  {
    id: "auto-sync",
    name: "Auto Sync",
    description: "Copies modified files to Docker container and triggers build",
    event: "PostToolUse",
    matcher: "Edit|Write",
    script: "post-tool-use/auto-sync.sh",
    category: "workflow",
    tier: "recommended",
    requires: { hasDocker: true },
    timeout: 30,
  },
  {
    id: "self-heal",
    name: "Self Heal",
    description: "Auto-fixes build failures after sync",
    event: "PostToolUse",
    matcher: "Edit|Write",
    script: "post-tool-use/self-heal.sh",
    category: "workflow",
    tier: "optional",
    requires: { hasDocker: true },
    timeout: 10,
    dependsOn: ["auto-sync"],
  },
  {
    id: "arch-guard",
    name: "Architecture Guard",
    description: "Validates import boundaries and architectural rules",
    event: "PostToolUse",
    matcher: "Edit|Write",
    script: "post-tool-use/arch-guard.sh",
    category: "quality",
    tier: "recommended",
    requires: { runtime: ["node", "python"] },
    timeout: 10,
  },
  {
    id: "dep-health",
    name: "Dependency Health",
    description: "Checks dependency freshness and pinning",
    event: "PostToolUse",
    matcher: "Edit|Write",
    script: "post-tool-use/dep-health.sh",
    category: "quality",
    tier: "optional",
    requires: { runtime: ["node"] },
    timeout: 10,
  },
  {
    id: "perf-budget",
    name: "Performance Budget",
    description: "Monitors file sizes and bundle budgets",
    event: "PostToolUse",
    matcher: "Edit|Write",
    script: "post-tool-use/perf-budget.sh",
    category: "performance",
    tier: "recommended",
    requires: { hasUI: true },
    timeout: 10,
  },
  {
    id: "build-tracker",
    name: "Build Tracker",
    description: "Tracks build times for DORA metrics",
    event: "PostToolUse",
    matcher: "Edit|Write",
    script: "post-tool-use/build-tracker.sh",
    category: "workflow",
    tier: "optional",
    requires: { hasDocker: true },
    timeout: 10,
  },
  {
    id: "auto-fix",
    name: "Auto Fix",
    description: "Auto-fixes lint errors in modified files",
    event: "PostToolUse",
    matcher: "Edit|Write",
    script: "post-tool-use/auto-fix.sh",
    category: "quality",
    tier: "optional",
    requires: { runtime: ["node"] },
    timeout: 10,
  },
  {
    id: "anti-mock",
    name: "Anti Mock",
    description: "Prevents mock/placeholder data in production code",
    event: "PostToolUse",
    matcher: "Edit|Write",
    script: "post-tool-use/anti-mock.sh",
    category: "quality",
    tier: "recommended",
    requires: { category: ["webapp", "api", "mobile"] },
    timeout: 10,
  },

  // ═══ PostToolUse — Bash ════════════════════════════════════════════════════
  {
    id: "dora-tracker",
    name: "DORA Tracker",
    description: "Tracks DORA deployment metrics after git operations",
    event: "PostToolUse",
    matcher: "Bash",
    script: "post-tool-use/dora-tracker.sh",
    category: "workflow",
    tier: "optional",
    requires: {},
    timeout: 10,
  },

  // ═══ Stop ══════════════════════════════════════════════════════════════════
  {
    id: "stop-review",
    name: "Stop Review",
    description: "Final build status check before ending session",
    event: "Stop",
    script: "stop/stop-review.sh",
    category: "workflow",
    tier: "recommended",
    requires: { hasDocker: true },
    timeout: 10,
    parallelGroup: "stop-fast",
  },
  {
    id: "qa-review",
    name: "QA Review",
    description: "Code quality review: console.log, any types, TODO/FIXME, function length",
    event: "Stop",
    script: "stop/qa-review.sh",
    category: "quality",
    tier: "recommended",
    requires: { runtime: ["node"] },
    timeout: 15,
    parallelGroup: "stop-code",
  },
  {
    id: "qa-design",
    name: "Design QA",
    description: "Design quality check: colors, transitions, focus states, spacing",
    event: "Stop",
    script: "stop/qa-design.sh",
    category: "design",
    tier: "recommended",
    requires: { hasUI: true, category: ["webapp", "mobile"] },
    timeout: 15,
    parallelGroup: "stop-code",
  },
  {
    id: "qa-a11y",
    name: "Accessibility QA",
    description: "Accessibility audit: ARIA labels, alt text, semantic HTML",
    event: "Stop",
    script: "stop/qa-a11y.sh",
    category: "design",
    tier: "recommended",
    requires: { hasUI: true },
    timeout: 15,
    parallelGroup: "stop-code",
  },
  {
    id: "dead-code",
    name: "Dead Code",
    description: "Detects unused exports and dead code",
    event: "Stop",
    script: "stop/dead-code.sh",
    category: "quality",
    tier: "optional",
    requires: { runtime: ["node"] },
    timeout: 15,
    parallelGroup: "stop-heavy",
  },
  {
    id: "doc-freshness",
    name: "Doc Freshness",
    description: "Checks if documentation is outdated relative to code changes",
    event: "Stop",
    script: "stop/doc-freshness.sh",
    category: "workflow",
    tier: "optional",
    requires: {},
    timeout: 10,
    parallelGroup: "stop-fast",
  },
  {
    id: "visual-check",
    name: "Visual Check",
    description: "Visual regression check using Playwright screenshots",
    event: "Stop",
    script: "stop/visual-check.sh",
    category: "design",
    tier: "optional",
    requires: { hasUI: true, hasDeps: ["playwright", "@playwright/test"] },
    timeout: 12,
    parallelGroup: "stop-heavy",
  },
  {
    id: "seo-check",
    name: "SEO Check",
    description: "SEO validation: meta tags, headings, structured data",
    event: "Stop",
    script: "stop/seo-check.sh",
    category: "quality",
    tier: "optional",
    requires: { hasUI: true, category: ["webapp"] },
    timeout: 15,
    parallelGroup: "stop-code",
  },
  {
    id: "csp-sri-check",
    name: "CSP/SRI Check",
    description: "Content Security Policy and Subresource Integrity validation",
    event: "Stop",
    script: "stop/csp-sri-check.sh",
    category: "security",
    tier: "recommended",
    requires: { hasUI: true, category: ["webapp"] },
    timeout: 10,
    parallelGroup: "stop-code",
  },
  {
    id: "dep-audit",
    name: "Dependency Audit",
    description: "Security audit of dependencies (CVEs, licenses)",
    event: "Stop",
    script: "stop/dep-audit.sh",
    category: "security",
    tier: "recommended",
    requires: { runtime: ["node"] },
    timeout: 30,
    parallelGroup: "stop-heavy",
  },
  {
    id: "session-end",
    name: "Session End",
    description: "Session cleanup: write handoff, save metrics",
    event: "Stop",
    script: "stop/session-end.sh",
    category: "workflow",
    tier: "core",
    requires: {},
    timeout: 10,
    parallelGroup: "stop-fast",
  },

  // ═══ Lifecycle ═════════════════════════════════════════════════════════════
  {
    id: "session-start",
    name: "Session Start",
    description: "Session initialization: load handoffs, show context",
    event: "SessionStart",
    script: "lifecycle/session-start.sh",
    category: "workflow",
    tier: "recommended",
    requires: {},
    timeout: 15,
  },
  {
    id: "pre-compact",
    name: "Pre Compact",
    description: "Prepare context before memory compaction",
    event: "PreCompact",
    script: "lifecycle/pre-compact.sh",
    category: "workflow",
    tier: "recommended",
    requires: {},
    timeout: 15,
  },
  {
    id: "prompt-context",
    name: "Prompt Context",
    description: "Smart context injection: loads relevant skills based on prompt content",
    event: "UserPromptSubmit",
    script: "lifecycle/prompt-context.sh",
    category: "workflow",
    tier: "recommended",
    requires: {},
    timeout: 10,
  },
];

/** Get hook metadata by ID */
export function getHookById(id: string): HookMetadata | undefined {
  return HOOKS_MANIFEST.find((h) => h.id === id);
}

/** Get all hooks for a specific event */
export function getHooksByEvent(event: string): HookMetadata[] {
  return HOOKS_MANIFEST.filter((h) => h.event === event);
}

/** Get all core (always-installed) hooks */
export function getCoreHooks(): HookMetadata[] {
  return HOOKS_MANIFEST.filter((h) => h.tier === "core");
}
